services:
  # Service Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: breizhops-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - breizhops-network

  # Service Backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: breizhops-backend
    ports:
      - "3000:3000"
    environment:
      - NEO4J_URL=${NEO4J_URL}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
      - neo4j
    networks:
      - breizhops-network

  # Service Neo4j
  neo4j:
    image: neo4j:4.4
    container_name: breizhops-neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - breizhops-network

  # Service PostgreSQL
  postgres:
    image: postgres:15
    container_name: breizhops-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - breizhops-network

networks:
  breizhops-network:
    driver: bridge
